# Automation Configuration Properties
basePath=C\:\\Users\\deepa\\Documents\\Automation\\Mcfeels
browserTimeout=15
pageLoadTimeout=30

csvPath=C\:\\Users\\deepa\\Documents\\Mcfeels\\Mcfeels.csv

imgbbApiKey=614c15cd45e405e3faab4576606e8e4b

discountCode=exitest

email=deepak.maheshwari@exinent.com
password=Admin@123

validSearchTerms=staples,screws,hinges,handles,bolts,knobs,pulls,slides,cabinet,door
invalidSearchTerms=pizza,car,apple,spaceship,unicorn

useIncognito=true
maxRetries=3